Image-Classification-master/project/cat_dog_classifier/views.py
from flask import request, Blueprint
from flask import render_template, request

import numpy as np
import keras
from keras.models import load_model

from skimage.io import imread
from skimage.transform import resize
import os.path

## BLUEPRINT INIT

cat_dog_classifier_blueprint = Blueprint(
    'cat_dog_classifier', __name__,
    template_folder="templates"
)

## DEFINE ALLOWED TEMPLATE FILE FORMAT ##############################################

ALLOWED_EXTENSIONS = set(['jpg'])


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


## MODEL ############################################################################

my_path = os.path.abspath(os.path.dirname(__file__))
cat_dog_classifier = os.path.join(my_path, "../../static/cat_dog_classifier/cat_dog_classifier.h5")


############################################################################# VIEWS #####################################################################################################################################


### MAIN PAGE


@cat_dog_classifier_blueprint.route('/classifier', methods=['GET', 'POST'])
def classifier():
    return render_template("cat_dog_classifier.html")


@cat_dog_classifier_blueprint.route('/upload', methods=['GET', 'POST'])
def upload():
    if request.method == 'POST' and 'photo' in request.files:
        img = request.files['photo']
        if allowed_file(img.filename):
            keras.backend.clear_session()  ## clear Tensor session to avoid error
            image_classifier = load_model(cat_dog_classifier)  ## load saved model
            class_labels = {0: 'Cat', 1: 'Dog'}  ## prepare labels
            img = imread(request.files['photo'])  ## read photo & transform it into array
            img = resize(img, (128, 128))
            img = np.expand_dims(img, axis=0)
            if (np.max(img) > 1):
                img = img / 255.0
            prediction = image_classifier.predict_classes(img)  ## predict class
            guess = class_labels[prediction[0][0]]  ## for website display
            keras.backend.clear_session()  ## clear Tensor session to avoid error

            return render_template("cat_dog_classify.html", guess=guess)
        else:
            return render_template("cat_dog_classifier.html")

Image-Classification-master/project/classify_image/views.py
from flask import Blueprint
from flask import render_template

## BLUEPRINT INIT

classify_image_blueprint = Blueprint(
    'classify_image', __name__,
    template_folder="templates"
)


############################################################################# VIEWS #####################################################################################################################################


### MAIN PAGE


@classify_image_blueprint.route('/classify', methods=['GET', 'POST'])
def classify():
    return render_template("classify_image.html")

Image-Classification-master/project/users/views.py
from flask import render_template, redirect, url_for, Blueprint, session
from werkzeug.security import generate_password_hash, check_password_hash

users_blueprint = Blueprint(
    'users', __name__,
    template_folder="templates"
)

from .forms import *
from .models import UserModel


########################################################################## USER VIEWS ###################################################################################################################


## SIGN UP ##########################################################################
@users_blueprint.route('/register', methods=["GET", "POST"])
def register():
    form = RegisterForm()
    session['current_user'] = 'Guest'
    if form.validate_on_submit():
        if UserModel.find_by_username(form.username.data) or UserModel.find_by_email(form.email.data):
            return render_template('register.html', form=form, message="User already exists")

        hashed_password = generate_password_hash(form.password.data,
                                                 method='sha256')  ## password get hashed for security purposes
        new_user = UserModel(username=form.username.data, email=form.email.data, password=hashed_password)
        new_user.save_to_db()
        return redirect(url_for('users.login'))

    return render_template('register.html', form=form)  ## passing signup form to signup template


## LOGIN ############################################################################

@users_blueprint.route('/login', methods=["GET", "POST"])
def login():
    form = LoginForm()

    if form.validate_on_submit():  ## if form was submitted....
        user = UserModel.find_by_username(username=form.username.data)
        if user:
            if check_password_hash(user.password, form.password.data):
                session['current_user'] = user.username
                return redirect(url_for('digit_recognition.digit_recognition'))

        return render_template('login.html', form=form, message="Invalid Username or Password")

    return render_template('login.html', form=form)  ## passing login form to login template


## LOGOUT ###########################################################################

@users_blueprint.route('/logout')
def logout():
    session['current_user'] = 'Guest'
    return redirect(url_for('users.login'))

Image-Classification-master/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Image Classifiers</title>
    <!-- Material Icons-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Materialize-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Bootstrap-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- FontAwesome Styles-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <script defer src="https://use.fontawesome.com/releases/v5.6.3/js/all.js" integrity="sha384-EIHISlAOj4zgYieurP0SdoiBYfGJKkgWedPHH4jCzpCXLmzVsw1ouK59MuUtP4a1" crossorigin="anonymous"></script>
    <!-- Custom Styles-->
    <link href="{{url_for('static', filename='css/custom-styles.css')}}" rel="stylesheet" />
    <link href="{{url_for('static', filename='css/navbar.css')}}" rel="stylesheet" />
    <!-- Google Fonts-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css' />
    <link href="https://fonts.googleapis.com/css?family=Roboto|Playball|Just+Another+Hand|Merienda+One|Alex+Brush" rel="stylesheet">
    <!-- jQuery -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    {% block styles %}{% endblock %}

</head>



<body>
    <!-- WRAPPER -->
    <div id="wrapper">

    <!-- TOP NAVBAR -->
    <nav class="navbar navbar-default top-navbar" role="navigation">
        <div class="navbar-header">
            <a class="navbar-brand waves-effect waves-dark" href="{{url_for('dashboard')}}"><i class="fas fa-images" id="top-icon"></i><strong>Image Classifiers</strong></a>
        </div>
        <ul class="nav navbar-top-links navbar-right">
            <li><a class="nav-link" target="_blank" href="https://www.linkedin.com/in/lukaszmalucha/"><i
                    class="fab fa-linkedin"></i><b> LinkedIn</b></a></li>
            <li><a class="nav-link" target="_blank" href="https://lukaszmalucha.github.io/portfolio/"><i
                    class="fab fa-github"></i> <b> GitHub</b></a></li>
            <li><a class='dropdown-trigger nav-link' href='#' data-target='dropdown1' id="user_dropdown"><i
                    class="fas fa-caret-down"></i><b> {{ current_user }}</b></a></li>
            <li><a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons" id="trigger">menu</i></a>
            </li>
        </ul>
    </nav>

    <!-- DROPDOWN -->
    <ul id="dropdown1" class="dropdown-content">
            <li><a href="{{ url_for('users.login') }}" id="dropdown_link"><i class="fa fa-user fa-fw"></i> Log In</a>
            </li>
            <li><a href="{{ url_for('users.logout') }}" id="dropdown_link"><i class="fas fa-sign-out-alt"></i> Log Out</a>
            </li>
            <li><a href="{{ url_for('users.register') }}" id="dropdown_link"><i class="fas fa-tasks"></i> Sign In</a>
            </li>
    </ul>

    <!-- MOBILE -->
    <ul class="sidenav" id="mobile-demo">
            <li><a href="{{ url_for('users.login') }}" id="dropdown_link"><i class="fa fa-user fa-fw"></i> Log In</a>
            </li>
            <li><a href="{{ url_for('users.logout') }}" id="dropdown_link"><i class="fas fa-sign-out-alt"></i> Log Out</a>
            </li>
            <li><a href="{{ url_for('users.register') }}" id="dropdown_link"><i class="fas fa-tasks"></i> Sign In</a>
            </li>
    </ul>

        <!--/. TOP NAVBAR ****************************************************************************************************************************************************************************************** -->

        <!-- PAGE-WRAPPER -->
        <div id="page-wrapper">
            <!-- PAGE-INDEX -->
            <div id="page-index">
                <div class="dashboard-cards">
                    {% block content %} {% endblock %}





                </div>

            </div>
            <!-- PAGE-INDEX -->

        </div>

        <!-- PAGE-WRAPPER -->

    </div>
    <!-- WRAPPER -->



        <!-- Bootstrap Js -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


        <!-- Materialize Js -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

        <script>
            $('.dropdown-trigger').dropdown();
        </script>

        <script>
        $(document).ready(function() {
            $('.sidenav').sidenav();
        });
        </script>

        <script>
              $(document).ready(function(){
                $('.fixed-action-btn').floatingActionButton();
              });
        </script>

</body>

</html>

Image-Classification-master/templates/dashboard.html
{% extends 'base.html' %} {% block content %}
<div class="card" id="main_card">
    <br>
    <br>
    <br>
    <div class="row">
        <div class="col-md-4">
            <a href="{{url_for('classify_image.classify')}}" id="classify_image_link">
            <div class="card" id="menu-card">
                <div class="card-image">
                    <img src="{{url_for('static', filename='img/image_guess.jpg')}}">
                </div>
                <div class="card-content">
                    <span class="card-title">What's on the Image?</span>
                    <p>Test yourself the one of the strongest Google Tensorflow models.</p>
                </div>
            </div>
            </a>
        </div>
         <div class="col-md-4">
            <a href="{{url_for('cat_dog_classifier.classifier')}}" id="cat_dog_classifier_link">
            <div class="card" id="menu-card">
                <div class="card-image">
                    <img src="{{url_for('static', filename='img/cat_dog.jpg')}}">
                </div>
                <div class="card-content">
                    <span class="card-title">Cat vs. Dog Recognition</span>
                    <p>Image classifier trained to distinct between cats and dogs images. CNN with Keras.</p>
                </div>
            </div>
            </a>
        </div>
         <div class="col-md-4">
            <a href="{{url_for('digit_recognition.digit_recognition')}}" id="digit_recognition_link">
            <div class="card" id="menu-card">
                <div class="card-image">
                    <img src="{{url_for('static', filename='img/digits.png')}}">
                </div>
                <div class="card-content">
                    <span class="card-title">Digit Identifier</span>
                    <p>Hand-Written Digit Recognition based on MNIST Dataset. CNN with Keras.</p>
                </div>
            </div>
            </a>
        </div>
    </div>
</div>
    {% endblock %}