Image-Classification-master/project/cat_dog_classifier/views.py
from flask import request, Blueprint
from flask import render_template, request

import numpy as np
import keras
from keras.models import load_model

from skimage.io import imread
from skimage.transform import resize
import os.path

## BLUEPRINT INIT

cat_dog_classifier_blueprint = Blueprint(
    'cat_dog_classifier', __name__,
    template_folder="templates"
)

## DEFINE ALLOWED TEMPLATE FILE FORMAT ##############################################

ALLOWED_EXTENSIONS = set(['jpg'])


def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


## MODEL ############################################################################

my_path = os.path.abspath(os.path.dirname(__file__))
cat_dog_classifier = os.path.join(my_path, "../../static/cat_dog_classifier/cat_dog_classifier.h5")


############################################################################# VIEWS #####################################################################################################################################


### MAIN PAGE


@cat_dog_classifier_blueprint.route('/classifier', methods=['GET', 'POST'])
def classifier():
    return render_template("cat_dog_classifier.html")


@cat_dog_classifier_blueprint.route('/upload', methods=['GET', 'POST'])
def upload():
    if request.method == 'POST' and 'photo' in request.files:
        img = request.files['photo']
        if allowed_file(img.filename):
            keras.backend.clear_session()  ## clear Tensor session to avoid error
            image_classifier = load_model(cat_dog_classifier)  ## load saved model
            class_labels = {0: 'Cat', 1: 'Dog'}  ## prepare labels
            img = imread(request.files['photo'])  ## read photo & transform it into array
            img = resize(img, (128, 128))
            img = np.expand_dims(img, axis=0)
            if (np.max(img) > 1):
                img = img / 255.0
            prediction = image_classifier.predict_classes(img)  ## predict class
            guess = class_labels[prediction[0][0]]  ## for website display
            keras.backend.clear_session()  ## clear Tensor session to avoid error

            return render_template("cat_dog_classify.html", guess=guess)
        else:
            return render_template("cat_dog_classifier.html")

Image-Classification-master/project/cat_dog_classifier/templates/cat_dog_classifier.html
{% extends 'base.html' %} {% block styles %} {{super()}}
<link href="{{url_for('static', filename='css/cat_dog_classifier.css')}}" rel="stylesheet" /> {% endblock %} {% block content %}
<div class="card text-center" id="main_card">
    <br>
    <br>
    <div class="row text-center">
        <h1><i class="fas fa-paw"></i> Let me predict if it's a Cat or Dog on your Image</h1>
    </div>
    <div class="row">
        <div class="col-md-5 text-left">
            <div class="card text-center" id="pet">
                <img src="/static/img/cat.jpg" class="img-responsive" />
            </div>

        </div>
        <div class="col-md-2 text-left">
        </div>
        <div class="col-md-5 text-left">
            <div class="card text-center" id="pet">
                <img src="/static/img/dog.jpg" class="img-responsive" />
            </div>
        </div>
    </div>
    <br>
    <div class="row text-center">
        <div class="col-md-3 text-left"></div>
        <div class="col-md-6 text-left">
            <div class="card text-center" id="form-upload">
                <div class="row text-center">
                    <h1><i class="fas fa-paw"></i> Upload your image in .jpg format:</h1>
                </div>
                {% if warning%}
                <div class="row text-center">
                    <div class="col-md-12 text-center">
                        <h3 style="color:red"> {{ warning }} !</h3>
                    </div>
                </div>
                {% endif %}
                <form method=POST enctype=multipart/form-data action="{{ url_for('cat_dog_classifier.upload' ) }}">
                    <div class="row text-center">
                        <div class="col-md-4 text-left"></div>
                        <div class="col-md-4 text-left">
                            <input type=file name=photo required>
                        </div>
                        <div class="col-md-4 text-left"></div>
                    </div>
                    <br>
                    <div class="row text-center">
                        <div class="col-md-4 text-left"></div>
                        <div class="col-md-5 text-center">
                            <input type="submit" class="waves-effect waves-light btn-predict" value="Predict!">
                        </div>
                        <div class="col-md-3 text-left"></div>
                    </div>


                </form>
            </div>
        </div>
        <div class="col-md-3 text-left"></div>
    </div>

<div class="fixed-action-btn">
    <a class="btn-floating btn-large" href="{{url_for('dashboard')}}">
        <i class="large material-icons">exit_to_app</i>
    </a>
</div>
</div>


{% endblock %}

Image-Classification-master/project/cat_dog_classifier/templates/cat_dog_classify.html
{% extends 'base.html' %} {% block styles %} {{super()}}
<link href="{{url_for('static', filename='css/cat_dog_classifier.css')}}" rel="stylesheet" /> {% endblock %} {% block content %}
<div class="card text-center" id="main_card">
    <br><br><br>
    <div class="row">
        <div class="row text-center">
            <div class=" col-md-3 text-left"></div>
            <div class="col-md-6 text-center">
                <div class="card text-center" id="cat_dog">
                    {% if guess == "Cat" %}
                    <img src="{{url_for('static', filename='img/cat.png')}}">
                    {% else %}
                    <img src="{{url_for('static', filename='img/dog.png')}}">
                    {% endif %}
                    <br><br>
                    <h1>I predict it's a {{ guess }}</h1>
                </div>
            </div>
            <div class=" col-md-3 text-left"></div>
        </div>
    </div>
    
    <br>
<div class="fixed-action-btn">
    <a class="btn-floating btn-large" href="{{url_for('dashboard')}}">
        <i class="large material-icons">exit_to_app</i>
    </a>
</div>
</div>

{% endblock %}